stages:
  - build

build_job:
  stage: build
  image: maven:3.6.3-jdk-17-slim
  script:
    - cd /builds/HyeokChan/basiccounter/counterapp
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
  only:
    - main
