stages:
  - build

build_job:
  stage: build
  image: maven:4.0.0-jdk-17
  script:
    - cd /builds/HyeokChan/basiccounter/counterapp
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
  only:
    - main
