stages:
  - build

build_spring:
  stage: build
  image: maven:3.8.3-openjdk-17
  script:
    - cd /builds/HyeokChan/basiccounter/counterapp
    - mvn clean package
  artifacts:
    paths:
      - /builds/HyeokChan/basiccounter/counterapp/target/*.jar
  only:
    - main

build_react:
  stage: build
  image: node:latest
  script:
    - cd /builds/HyeokChan/basiccounter/basiccounterfront
    - npm install # 의존성 설치
    - npm run build # 빌드 실행
  artifacts:
    paths:
      - /builds/HyeokChan/basiccounter/build/*
  only:
    - main