stages:
  - build

build_job:
  stage: build
  image: maven:3.8.3-openjdk-17
  script:
    - cd /builds/HyeokChan/basiccounter/counterapp
    - mvn clean package
  artifacts:
    paths:
      - /builds/HyeokChan/basiccounter/counterapp/target/*.jar
  only:
    - main
